[project]
name = "effective-mobile"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
    "pytest-django>=4.11.1",
    "ruff>=0.11.4",
]
