# Generated by Django 5.2 on 2025-04-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Заголовок объявления')),
                ('description', models.CharField(max_length=255, verbose_name='Описание товара')),
                ('image_url', models.URLField(verbose_name='URL изображения')),
                ('category', models.CharField(max_length=30, verbose_name='Категория товара')),
                ('condition', models.CharField(choices=[('New', 'Новый'), ('NOT New', 'Б/У')], max_length=30, verbose_name='Состояние товара')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
