# Generated by Django 5.2 on 2025-04-13 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Категория')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Заголовок объявления')),
                ('description', models.CharField(max_length=255, verbose_name='Описание товара')),
                ('image_url', models.URLField(blank=True, verbose_name='URL изображения')),
                ('condition', models.CharField(choices=[('NEW', 'Новый'), ('NOT NEW', 'Б/У')], verbose_name='Состояние товара')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('category', models.ManyToManyField(blank=True, related_name='category', to='ads.category', verbose_name='Категория товара')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('awaits', 'ожидает'), ('rejected', 'отклонена'), ('accepted', 'принята')], default='awaits', max_length=10, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_receiver_id', to='ads.ad')),
                ('ad_sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_sender_id', to='ads.ad', verbose_name='id объявления отправителя')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
