# Generated by Django 5.2 on 2025-04-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('awaits', 'ожидает'), ('rejected', 'отклонена'), ('accepted', 'принята')], default='awaits', max_length=10, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='ads.ad', verbose_name='id объявления получателя')),
                ('ad_sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ads.ad', verbose_name='id объявления отправителя')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
